databases:
  - name: configs-db
    plan: free
    databaseName: configs
    user: configs

services:
  - type: web
    plan: free
    name: configs
    runtime: python
    buildCommand: "bash build.sh"
    startCommand: "python -m gunicorn django_machine_learning.app.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: configs-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4