databases:
  - name: configs-db
    plan: free
    databaseName: configs
    user: configs

services:
  - type: web
    plan: free
    name: configs
    runtime: python
    buildCommand: "bash ./app/build.sh"
    startCommand: "cd app && source venv/bin/activate && python -m gunicorn configs.asgi:application -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: configs-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: PORT
        value: 8000