# Generated by Django 5.1.6 on 2025-02-18 18:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IrisPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sepal_length', models.FloatField()),
                ('sepal_width', models.FloatField()),
                ('petal_length', models.FloatField()),
                ('petal_width', models.FloatField()),
                ('predicted_class', models.CharField(choices=[('setosa', 'Iris Setosa'), ('versicolor', 'Iris Versicolor'), ('virginica', 'Iris Virginica')], max_length=20)),
                ('actual_class', models.CharField(choices=[('setosa', 'Iris Setosa'), ('versicolor', 'Iris Versicolor'), ('virginica', 'Iris Virginica')], default='versicolor', max_length=20)),
                ('prediction_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
