# Generated by Django 5.1.6 on 2025-02-21 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WineQuality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alcohol', models.FloatField()),
                ('malic_acid', models.FloatField()),
                ('ash', models.FloatField()),
                ('alcalinity_of_ash', models.FloatField()),
                ('magnesium', models.FloatField()),
                ('total_phenols', models.FloatField()),
                ('flavanoids', models.FloatField()),
                ('nonflavanoid_phenols', models.FloatField()),
                ('proanthocyanins', models.FloatField()),
                ('color_intensity', models.FloatField()),
                ('hue', models.FloatField()),
                ('od280_od315', models.FloatField(verbose_name='OD280/OD315')),
                ('proline', models.FloatField()),
                ('predicted_quality', models.FloatField(null=True)),
                ('actual_quality', models.FloatField()),
                ('prediction_confidence', models.FloatField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Wine Quality Predictions',
            },
        ),
    ]
