name: Model Testing

on:
  push:
    paths:
      - 'pytorch/neural_networks/iris_dataset/**'
  pull_request:
    paths:
      - 'pytorch/neural_networks/iris_dataset/**'

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run tests
      run: |
        chmod +x pytorch/neural_networks/iris_dataset/run_tests.sh
        ./pytorch/neural_networks/iris_dataset/run_tests.sh 